### PR TITLE
Respect `strict=False` for exceptions.

### LINKED ISSUE #123: Exceptions check for required/optional even if strict = false
When strict mode is false, structs do not require the "optionalness" of a field, but exceptions still do:

ex.thrift:
```
> cat ex.thrift
exception TestEx {
  1: string message
}
```

```bash

In [1]: import thriftrw

In [2]: loader = thriftrw.loader.Loader(strict=False)

In [3]: loader.load('ex.thrift')

[...]
thriftrw/spec/field.pyx in thriftrw.spec.field.FieldSpec.compile (thriftrw/spec/field.c:2232)()

ThriftCompilerError: Field "message" of "TestEx" on line 2 does not explicitly specify requiredness. Please specify whether the field is optional or required in the IDL.
```

### PR DESCRIPTION
**Pull request by abhinav**
Resolves #123.

### CODE REVIEW

**Comment by abhinav** [comment]
CC @blampe @breerly @junchaowu @prashantv

**Comment by blampe** [comment]
🚢

**Comment by prashantv** [comment]
lgtm :shipit:

**Comment by breerly** [comment]
travis is sad.

**Pull request merged**
